Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Password/Reset.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Extensions;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service.Model;

namespace Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.User
{
    public class PasswordResetModel : PageModel
    {
        [TempData]
        public string ErrorMessage { get; set; } = "";

        [TempData]
        public string? SuccessMessage { get; set; } = default!;

        [BindProperty]
        public string Email { get; set; } = "";

        public UserService _userService;

        public PasswordResetModel(UserService userService)
        {
            _userService = userService;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostResetPassword()
        {
            try
            {
                Email = Regex.Replace(Email, @"\s+", "");
                if (string.IsNullOrWhiteSpace(Email) || !Email.IsEmailValid())
                {
                    ErrorMessage = "Email nicht valide!";
                    return RedirectToPage("/Password/Reset");
                }
                _userService.ResetPassword(Email);
                if (String.IsNullOrWhiteSpace(ErrorMessage)) SuccessMessage = "E-Mail Versendet";
                return RedirectToPage("/Login");
            }
            catch (ApplicationException ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Password/Reset.cshtml
@page
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.User.PasswordResetModel
@{
}
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group">
                    <div class="card p-4">
                        <form method="post" asp-page-handler="ResetPassword">
                            <div class="card-body">
                                <h1>Passworthilfe</h1>
                                <p class="text-muted">Geben Sie die Login E-Mail-Adresse ein, die mit Ihrem Konto verbunden ist.</p>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="icon-user"></i>
                                        </span>
                                    </div>
                                    <input class="form-control" type="text" placeholder="E-Mail Addresse" asp-for="Email">
                                </div>
                                <div class="input-group mb-4">
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <button class="btn btn-primary px-4" type="submit">Senden</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                        {
                            <p class="text-danger">@Model.ErrorMessage</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Password/Set.cshtml
@page "{Id}/{Token}"
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.User.SetPasswordModel
@{
    ViewData["Title"] = "Set Password";
    Layout = "_LayoutFullScreen";
}
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group">
                    <div class="card p-4">
                        <form method="post" asp-route-Id="@Model.Id" asp-rout-Token="@Model.Token">
                            <div class="card-body">
                                <h1>Passwort eingeben.</h1>
                                <p class="text-muted">Geben Sie ein neues Passwort ein.</p>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="icon-user"></i>
                                        </span>
                                    </div>
                                    <input class="form-control" type="password" placeholder="Password" asp-for="Password.First">
                                </div>
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="icon-lock"></i>
                                        </span>
                                    </div>
                                    <input class="form-control" type="password" placeholder="Passwort" asp-for="Password.Second">
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <input class="btn btn-primary px-4" type="submit" value="Speichern" />
                                    </div>
                                </div>
                            </div>
                        </form>
                        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                        {
                            <p class="text-danger">@Model.ErrorMessage</p>
                        }
                        @if (!string.IsNullOrEmpty(Model.SuccessMessage))
                        {
                            <p class="text-success">@Model.SuccessMessage</p>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>