Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Development.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Model;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service.EMail;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service.Model;

namespace Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages
{
    public class DevelopmentModel : PageModel
    {
        readonly PartyService _partyService;
        public List<Model.Party> userList = new();
        readonly AuthService _authService;
        readonly TicketService _ticketService;
        readonly OrderService _orderService;
        readonly EMailService _emailService;

        public DevelopmentModel(PartyService partyService, AuthService authService, TicketService ticketService, OrderService orderService, EMailService emailService)
        {
            _ticketService = ticketService;
            _partyService = partyService;
            _authService = authService;
            _orderService = orderService;
            this._emailService = emailService;
        }

        [BindProperty]
        public string OrderId { get; set; } = "";
        [BindProperty]
        public string Mail { get; set; } = "";

        public IActionResult OnGet()
        {
            userList = _partyService.GetTable<Party>().Include(e => e.User).OrderByDescending(e => e.Role).ToList();
            return Page();
        }

        public IActionResult OnPostSignIn(string email, string passwort)
        {
            _authService?.Logout();
            _authService?.TryLoginAsync(email!, passwort!);
            return RedirectToPage("/Development");
        }

        public async Task<IActionResult> OnPostSetAllTicketsToClosed()
        {


            if (int.TryParse(OrderId, out int id))
            {
                var tickets = _ticketService.GetTable<Model.Ticket>().Include(i => i.Status).Where(i => i.OrderId == id).ToList();
                foreach (var item in tickets)
                {
                    item.Status = _ticketService.GetTable<Status>().SingleOrDefault(i => i.Sequence == 0)!;
                    await _ticketService.Update(item);
                }
            }
            else
            {
                throw new ApplicationException("ned a int");
            }
            return Page();
        }


        public IActionResult OnPostSetOrderClosed()
        {
            if (int.TryParse(OrderId, out int id))
            {
                var order = _ticketService.GetTable<Model.Order>().FirstOrDefault(e => e.Id == id);
                if (order is not null)
                {
                    _orderService.SetOrderPayed(order.Guid);
                }
            }
            else
            {
                throw new ApplicationException("ned a int");
            }
            return Page();
        }

        public IActionResult OnPostSendEMail()
        {
            _emailService.SendEmail(new SendGrid.Helpers.Mail.EmailAddress(Mail), "Test", "this  is a test");
            return Page();
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/EditParty.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages
{
    public class EditUserModel : PageModel
    {

        public void OnGet()
        {
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CoreUI_Free_Bootstrap_Admin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; } = default!;

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BOP.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return new RedirectResult("/Startseite");
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service;

namespace Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages
{
    public class LoginModel : PageModel
    {
        public readonly AuthService _authService;

        public LoginModel(AuthService service)
        {
            _authService = service;
        }

        [BindProperty]
        [FromQuery]
        public string? ReturnUrl { get; set; }

        [BindProperty]
        public string Email { get; set; } = default!;
        [BindProperty]
        public string Password { get; set; } = default!;

        [TempData]
        public string? ErrorMessage { get; set; } = default!;

        [TempData]
        public string? SuccessMessage { get; set; } = default!;

        public async Task<IActionResult> OnPost()
        {
            try
            {
                bool result = await _authService.TryLoginAsync(Email, Password);
                if (!result)
                {
                    ErrorMessage = "Benutzername oder Passwort ungueltig.";
                    return RedirectToPage("/Login");
                }
                return LocalRedirect(!string.IsNullOrEmpty(ReturnUrl) ? ReturnUrl : "/");
            }
            catch (ApplicationException ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToPage("/Login");
            }
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Webbasierende_Verwaltungsapplikation_fuer_KMU.Service;

namespace Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly AuthService _service;

        public LogoutModel(AuthService service)
        {
            _service = service;
        }

        public async Task<IActionResult> OnGet()
        {
            await _service.Logout();
            return LocalRedirect("/");
        }
    }
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/404.cshtml
@page
@{
    ViewData["Title"] = "404";
    Layout = "_LayoutFullScreen";
}

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="clearfix">
                    <h1 class="float-left display-3 mr-4">404</h1>
                    <h4 class="pt-3">Oops! You're lost.</h4>
                    <p class="text-muted">The page you are looking for was not found.</p>
                    <a asp-page="/Index"> return Home</a>
                </div>
            </div>
        </div>
    </div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/500.cshtml
@page
@{
    ViewData["Title"] = "500";
    Layout = "_LayoutFullScreen";
}

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="clearfix">
                    <h1 class="float-left display-3 mr-4">500</h1>
                    <h4 class="pt-3">Houston, we have a problem!</h4>
                    <p class="text-muted">The page you are looking for is temporarily unavailable.</p>
                </div>
                <div class="input-prepend input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                    <input class="form-control" id="prependedInput" size="16" type="text" placeholder="What are you looking for?">
                    <span class="input-group-append">
                        <button class="btn btn-info" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Development.cshtml
@page
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.DevelopmentModel
@{
}
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="col justify-content-center">
            <div class="col-md-14">
                <table class="table table-responsive-sm table-hover table-outline mb-0">
                    <thead class="thead-light">
                        <tr>
                            <th>Type</th>
                            <th>Email</th>
                            <th>CanCreateNewConversation</th>
                            <th>CanUploadNewDocuments</th>
                            <th>Button</th>
                            <th>Add Order</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.userList)
                        {
                            <tr>
                                @*<td>@item.Fullname</td>*@
                                <td>@item?.Role.ToString()</td>
                                <td>@item?.User?.LoginEMail</td>
                                <td>@item?.Rights?.CanCreateNewConversation.ToString()</td>
                                <td>@item?.Rights?.CanUploadFiles.ToString()</td>
                                <td>
                                    <div>
                                        <form method="post" asp-page-handler="SignIn" asp-route-email="@item?.User?.LoginEMail" asp-route-passwort="12345">
                                            <input class="btn btn-block btn-outline-primary" type="submit" value="SignIn" />
                                        </form>
                                    </div>
                                </td>
                                <td>
                                    <a asp-page="/Order/Add" asp-route-guid="@item?.Guid">
                                        <input type="button" />
                                    </a>
                                </td>

                            </tr>
                        }
                    </tbody>

                </table>
                <form method="post" asp-page-handler="SetAllTicketsToClosed">
                    Set all Tickets closed for a Order:
                    <input asp-for="OrderId" type="text" />
                    <input type="submit" />
                </form>

                <form method="post" asp-page-handler="SetOrderClosed">
                    Schließt eine Order:
                    <input asp-for="OrderId" type="text" />
                    <input type="submit" />
                </form>

                <form method="post" asp-page-handler="SendEMail">
                   Send a mail to:
                    <input asp-for="Mail" type="text" />
                    <input type="submit" />
                </form>
            </div>
        </div>
    </div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/EditParty.cshtml
@page
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.EditUserModel
@{
}

@*
    • All Fields from Customer/Employee/Company
    • List with all Addresses (Edit Button, Delete Button, Set as Default Button)
    • List with all Emails (Edit Button, Delete Button, Set as Default Button, Set as Login Email)
    • List with all phone numbers (Textbox (Telefonnumber), DropDownMenu for Type, Edit Button, Delete Button)
    • "Passwort Reset Link Anfordern" Button.
*@

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class=" container">
                    <div class="input-group mb-3">
                        <input class="form-control" type="text" placeholder="Vorname">
                        <input class="form-control" type="text" placeholder="Zuname">
                    </div>
                    <div class="input-group mb-3">
                        <input class="form-control" type="text" placeholder="Firmen Name">
                    </div>
                    <div class="input-group mb-3">
                        <input class="form-control" type="number" placeholder="UID">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <strong style="font-weight:400">Geschlecht</strong>
                            </span>
                        </div>
                        <select name="Priorität" class="custom-select" ">
                            <option value="m">m</option>
                            <option value="w">w</option>
                            <option value="u">u</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="icon-event"></i>
                            </span>
                        </div>
                        <input class="form-control" type="date" placeholder="Gebutsdatum">
                    </div>
                    <div class="input-group mb-3">
                        <input class="form-control" type="number" placeholder="Stundensatz">
                    </div>
                    Adressen:
                    <div class="container">
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                                <tr>
                                    <th>Straße</th>
                                    <th>Hausnummer</th>
                                    <th>Stiege</th>
                                    <th>Plz</th>
                                    <th>Stadt</th>
                                    <th>Bearbeiten</th>
                                    <th>Löschen</th>
                                    <th>Standard</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>Hansgasse</th>
                                    <th>13</th>
                                    <th></th>
                                    <th>7</th>
                                    <th>Wien</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                </tr>
                                <tr>
                                    <th>Max Straße</th>
                                    <th>101B</th>
                                    <th>4</th>
                                    <th>23</th>
                                    <th>Stockerau</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <br />
                    Email Adressen:
                    <div class="container">
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                                <tr>
                                    <th>E-Mail</th>
                                    <th>Bearbeiten</th>
                                    <th>Löschen</th>
                                    <th>Standard</th>
                                    <th>Login</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>a@a.at</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">Log</button>
                                    </th>
                                </tr>
                                <tr>
                                    <th>b@b.at</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">Log</button>
                                    </th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <br />
                    Telefonnummern:
                    <div class="container">
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                                <tr>
                                    <th>Telefonnummer</th>
                                    <th>Bearbeiten</th>
                                    <th>Löschen</th>
                                    <th>Standard</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>0664 1234567</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                </tr>
                                <tr>
                                    <th>06801334099</th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">B</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">L</button>
                                    </th>
                                    <th>
                                        <button class="btn btn-block btn-success" type="button">S</button>
                                    </th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="container">
                        <th>
                            <button class="btn btn-block btn-success">Password zurücksetzen</button>
                        </th>
                    </div>
                    <br />
                    <div class="container">
                        <th>
                            <button class="btn btn-block btn-success">Speichern</button>
                            <button class="btn btn-block btn-success">Abbrechen</button>
                        </th>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Index.cshtml
@page
@{ ViewData["Title"] = "Home page"; }

@section Scripts {
    <script src="~/lib/chart.js/dist/Chart.min.js"></script>
    <script src="~/lib/coreui/js/custom-tooltips.min.js"></script>
    <script src="~/lib/coreui/js/main.js"></script>
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/Logout.cshtml
@page
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.LogoutModel
@{
}

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/blank.cshtml
@page
@{
    ViewData["Title"] = "Blank Page";
}

<div class="container-fluid">
    <div class="animated fadeIn"></div>
</div>

Webbasierende-Verwaltungsapplikation-fuer-KMU/Pages/login.cshtml
@page
@model Webbasierende_Verwaltungsapplikation_fuer_KMU.Pages.LoginModel
@{
    if (!Model._authService.IsEmployee)
    {
        ViewData["Title"] = "Login";
        //Layout = "_LayoutFullScreen";
    }
    else
    {
        ViewData["Title"] = "Neuer Kunde";
    }
}

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group">
                    @if (!Model._authService.IsEmployee)
                    {
                        <div class="card p-4">
                            <form method="post">
                                <div class="card-body">
                                    <h1>Login</h1>
                                    <p class="text-muted">Melden Sie sich bei Ihrem Account an</p>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-user"></i>
                                            </span>
                                        </div>
                                        <input class="form-control" type="text" placeholder="E-Mail Addresse" asp-for="Email">
                                    </div>
                                    <div class="input-group mb-4">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-lock"></i>
                                            </span>
                                        </div>
                                        <input class="form-control" type="password" placeholder="Passwort" asp-for="Password">
                                    </div>
                                    <div class="row">
                                        <div class="col-6">
                                            <button class="btn btn-primary px-4" type="submit">Login</button>
                                        </div>
                                        <div class="col-6 text-right">
                                            <a href="/Password/Reset">
                                                <input type="button" class="btn btn-link px-0" value="Passwort vergessen?" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                            {
                                <p class="text-danger">@Model.ErrorMessage</p>
                            }
                            @if (!string.IsNullOrEmpty(Model.SuccessMessage))
                            {
                                <p class="table-success">@Model.SuccessMessage</p>
                            }
                        </div>
                    }
                    <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
                        <div class="card-body text-center">
                            <div>
                                @if (!Model._authService.IsEmployee)
                                {
                                    <h2>Sign up</h2>
                                    <p>Haben Sie noch keinen Account?</p>
                                    <a class="btn btn-primary active mt-3" href="/Register/Company" type="button">Als Unternehmen registrieren</a>
                                    <a class="btn btn-primary active mt-3" type="button" href="/Register/Customer"> Als Privatperson registrieren</a>
                                }
                                @if (Model._authService.IsEmployee)
                                {
                                    <h2>Kunden Account erstellen</h2>
                                    <a class="btn btn-primary active mt-3" href="/Register/Company" type="button">Ein Unternehmen registrieren</a>
                                    <a class="btn btn-primary active mt-3" type="button" href="/Register/Customer"> Eine Privatperson registrieren</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>